Repository arr-ai/arrai, pull requests merged in 2020-06, with the labels that each got.

#387 Improve test coverage of dot_expr
  rel/expr_dot_test.go
  rel/test_helpers.go
  syntax/expr_dot_test.go
Labels: code health

#397 Fix #356: set to array with holes
  rel/expr_array.go
  rel/value_set_array.go
  rel/value_set_array_test.go
  syntax/expr_array_test.go
  syntax/expr_seqmap_test.go
Labels: bug

#399 Remove dead getter code
  rel/expr.go
  rel/expr_array.go
  rel/expr_arrow.go
  rel/expr_binary.go
  rel/expr_darrow.go
  rel/expr_if_else.go
  rel/expr_nest.go
  rel/expr_seqmap.go
  rel/expr_seqmap_test.go
  rel/expr_set.go
  rel/expr_tuple.go
  rel/expr_tuplemap.go
  rel/expr_unary.go
  rel/expr_unnest.go
  rel/value_set_native_expr_func.go
  rel/value_set_native_func.go
  rel/value_tuple.go
  rel/value_tuple_array_item.go
  rel/value_tuple_array_item_test.go
  rel/value_tuple_bytes_byte.go
  rel/value_tuple_bytes_byte_test.go
  rel/value_tuple_dict_entry.go
  rel/value_tuple_str_char.go
  rel/value_tuple_str_char_test.go
Labels: code health

#383 Rename NewMapExpr to NewDArrowExpr
  rel/expr_darrow.go
  rel/expr_darrow_test.go
  syntax/compile.go
  syntax/expr_darrow_test.go
Labels: code health

#453 Implement macro support in Arrai parsing
  docs/README.md
  docs/tutorial/README.md
  docs/tutorial/macros.md
  syntax/arrai.wbnf
  syntax/compile.go
  syntax/expr_let_test.go
  syntax/grammar_test.go
  syntax/parse.go
  syntax/parse_macro.go
  syntax/parser.go
  syntax/test_helpers.go
Labels: P1

#404 Improve test coverage within rel
  rel/expr_tuple_dict_entry_test.go
  rel/match_test.go
  rel/ops_set.go
  rel/ops_set_test.go
  rel/value_repr_test.go
  rel/value_set_eclosure.go
  rel/value_set_native_func.go
  syntax/import.go
  syntax/std_bits.go
Labels: code health

#477 Removed unnecessary pattern code.
  rel/expr_cond_control_var.go
  rel/pattern_ident.go
  rel/value_set_func.go
  syntax/compile.go
Labels: code health

#475 Changed AssertCodeErrors signature, expected is before actual.
  rel/pattern_set.go
  syntax/expr_arrow_test.go
  syntax/expr_bytes_test.go
  syntax/expr_cond_test.go
  syntax/expr_dot_test.go
  syntax/expr_fn_test.go
  syntax/expr_let_test.go
  syntax/expr_recursion_test.go
  syntax/expr_safe_tail_test.go
  syntax/expr_set_test.go
  syntax/package_test.go
  syntax/std_bits_test.go
  syntax/std_encoding_json_test.go
  syntax/std_eval_test.go
  syntax/std_re_test.go
  syntax/std_seq_contains_test.go
  syntax/std_seq_join_test.go
  syntax/std_seq_prefix_test.go
  syntax/std_seq_split_test.go
  syntax/std_seq_sub_test.go
  syntax/std_seq_suffix_test.go
  syntax/std_seq_test.go
  syntax/std_str_test.go
  syntax/std_test.go
  syntax/test_helpers.go
Labels: code health
